#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := sample_project

include $(IDF_PATH)/make/project.mk
export IDF_PATH := ./esp-idf
include $(IDF_PATH)/make/project.mk

